#!/usr/bin/env python3
"""Generate campaign/nodes.yaml for the run up to Norman (segments 1-16).

Built from the same ORDER table that produces ROUTE.txt, so the playable campaign
and the written route cannot drift apart. Everything factual -- map ids, mapsecs,
which draws exist -- comes from campaign/extracted.json.

Two things the route document only describes, and this has to make real:

  * A location lists every draw it has, each tagged with the capability it needs.
    The driver filters them by what the trainer holds, so a location visited
    early offers grass only, and the same location left unspent offers surf and
    rods later. That is R2's delay decision, expressed as data.

  * Capabilities are granted by the node where they are obtained, gated on the
    badge that makes them usable (field_move.c). Strength is picked up in Rusturf
    Tunnel but is not a capability until Flannery, so it is granted there.

    tools/gen_nodes.py > campaign/nodes.yaml
"""

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from campaign_route import (ORDER, CAPABILITIES, BADGE_ORDER,     # noqa: E402
                            ROD_SLICES, METHOD_CAP)

ROOT = pathlib.Path(__file__).resolve().parent.parent
LAST_SEGMENT = 16          # the run ends when Norman falls

# Draw method -> the name campaign.py/play.py use, and the capability it needs.
METHOD_OF_FIELD = {
    "land_mons": ("grass", None),
    "water_mons": ("surf", "SURF"),
    "rock_smash_mons": ("rocksmash", "ROCK_SMASH"),
}
ROD_METHOD = {"ROD_OLD": "rod_old", "ROD_GOOD": "rod_good", "ROD_SUPER": "rod_super"}


def main() -> int:
    data = json.loads((ROOT / "campaign/extracted.json").read_text())
    w = sys.stdout.write

    # Segment numbering, and the fight that closes each one.
    stop_seg, badge_seg, seg_last_fight = {}, {}, {}
    seg = 1
    for label, maps, gate, badge, mand, note in ORDER:
        stop_seg.setdefault(label, seg)
        if badge:
            badge_seg[BADGE_ORDER.index(badge) + 1] = seg
        if mand:
            seg_last_fight[seg] = mand[-1]
            seg += 1

    cap_seg = {}
    for cap, (item, at_stop, badge_no) in CAPABILITIES.items():
        got = stop_seg.get(at_stop, 1)
        cap_seg[cap] = max(got, badge_seg.get(badge_no, 1) if badge_no else 1)

    # TMs a segment hands out, keyed to the fight that closes it. Only TMs are
    # carried across: potions and repels are the navigation-and-convenience items
    # the harness does not use, and listing them would be noise the agent has to
    # read past on every decision.
    tm_in_seg: dict[int, list[str]] = {}
    tm_seen: set[str] = set()      # Route 104 spans two stops; award each TM once
    for label, maps, gate, badge, mand, note in ORDER:
        s = stop_seg[label]
        if s > LAST_SEGMENT:
            continue
        for mp in maps:
            rec = data.get(mp)
            if not rec:
                continue
            for kind in ("gift", "ball", "hidden"):
                for item in rec["items"].get(kind) or []:
                    if item.startswith("ITEM_TM_") and item not in tm_seen:
                        tm_seen.add(item)
                        tm_in_seg.setdefault(s, []).append(item)

    def node_id(tid):
        """A stable node id. The rival's trainer id carries {rival}/{starter}
        templates -- those belong in `trainer:` where they get substituted, not
        in the id, which other nodes reference by name (and which YAML would
        read as a flow mapping)."""
        if "{rival}" in tid:
            return ("rival_" + tid.replace("TRAINER_{rival}_", "")
                                  .replace("_{starter}", "").lower())
        return tid.replace("TRAINER_", "").lower()

    w("# Campaign table (spec §7), generated by tools/gen_nodes.py.\n")
    w("# DO NOT EDIT BY HAND -- edit ORDER in tools/campaign_route.py and rerun.\n")
    w("#\n")
    w("# The run ends when Norman falls (segment 16). Fights form one linear chain,\n")
    w("# so there is exactly one next fight at any moment. Locations are gated only\n")
    w("# by fights, and every draw carries the capability it needs -- so a location\n")
    w("# left unspent keeps offering better draws as rods and Surf arrive, which is\n")
    w("# R2's delay decision made real.\n\n")

    # ---- fights ------------------------------------------------------------
    w("# --- fight chain, in order ---------------------------------------------\n\n")
    order_n = 0
    fight_ids = []
    for label, maps, gate, badge, mand, note in ORDER:
        s = stop_seg[label]
        if s > LAST_SEGMENT or not mand:
            continue
        battle_map = next((data[m]["map"] for m in maps if m in data), None)
        for tid in mand:
            order_n += 1
            nid = node_id(tid)
            fight_ids.append((nid, s))
            kind = "single"
            for m in maps:
                for t in data.get(m, {}).get("trainers", []):
                    if t["id"] == tid:
                        kind = t["kind"]
            w(f"- id: {nid}\n")
            w("  kind: trainer_battle\n")
            w(f"  trainer: {tid}\n")
            w(f"  battle_kind: {kind}\n")
            if battle_map:
                w(f"  map: {battle_map}\n")
            w("  mandatory: true\n")
            w(f"  order: {order_n}\n")
            w(f"  where: {label}\n")
            # Capabilities become usable here: either the item is picked up in
            # this segment, or the badge this fight grants unlocks one already
            # held.
            grants = sorted(c for c, cs in cap_seg.items()
                            if cs == s and tid == mand[-1])
            if grants:
                w(f"  grants: [{', '.join(grants)}]\n")
            if tid == mand[-1] and tm_in_seg.get(s):
                w(f"  gives_items: [{', '.join(tm_in_seg[s])}]\n")
            if badge and tid == mand[-1]:
                w(f"  badge: {badge}\n")
            w("\n")

    # ---- locations ---------------------------------------------------------
    w("# --- locations ----------------------------------------------------------\n")
    w("# unlocked_by names a FIGHT, never another location: crossing a route\n")
    w("# without spending its encounter is allowed and is a real choice.\n\n")
    seen_sec = set()
    for label, maps, gate, badge, mand, note in ORDER:
        s = stop_seg[label]
        if s > LAST_SEGMENT:
            continue
        for mp in maps:
            rec = data.get(mp)
            if rec is None or not rec["encounters"]:
                continue
            sec = rec.get("region_section")
            if not sec or sec in seen_sec:
                continue
            seen_sec.add(sec)

            draws = []
            for field, mons in rec["encounters"].items():
                if field == "fishing_mons":
                    for rod, lo, hi in ROD_SLICES:
                        if mons[lo:hi]:
                            draws.append((ROD_METHOD[rod], rod))
                else:
                    method, cap = METHOD_OF_FIELD.get(field, (None, None))
                    if method:
                        draws.append((method, cap))
            if not draws:
                continue

            w(f"- id: loc_{sec.replace('MAPSEC_', '').lower()}\n")
            w("  kind: location\n")
            w(f"  mapsec: {sec}\n")
            unlock = seg_last_fight.get(s - 1)
            if unlock:
                w(f"  unlocked_by: {node_id(unlock)}\n")
            w("  draws:\n")
            for method, cap in draws:
                req = f", requires: [{cap}]" if cap else ""
                w(f"    - {{map: {rec['map']}, method: {method}{req}}}\n")
            w("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
